apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: app-b
  namespace: development
  labels:
    app: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: python
        image: lb_test:1
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
        readinessProbe: # Determines when container recieves traffic
            periodSeconds: 10
            timeoutSeconds: 2
            httpGet:
              path: /healthz
              port: http
